### ISSUE TITLE
URL from getDefinitions is not loading correctly.

### ISSUE THREAD

**Issue by hellonathanchung** [Unleash/unleash-client-nextjs#53]
### Describe the bug

when trying to run getDefinitions with a server api url that wasn't in the env, I'd receive this message.

i was using this:
UNLEASH_SERVER_API_URL

but when trying to pass in a str for the url, i'd receive the following: 

```
definitions {
  message: 'invalid token: expected a different token type for this endpoint'
}
```

### Subscription type

None

### Hosting type

None

**Comment by Tymek** [comment]
You need `CLIENT` token type for backend use. Not `FRONTEND` token. Also make sure your URL is configured according to documentation.

https://github.com/Unleash/unleash-client-nextjs#environment-variables
https://docs.getunleash.io/reference/api-tokens-and-client-keys#client-tokens

Does this solve your issue?

**Comment by hellonathanchung** [comment]
When using the token/url in a .env it works fine. When trying to pass it into getDefinitions manually, that's when it seems to break.

**Comment by aulonm** [comment]
Same problem here. Getting `invalid token: expected a different token type for this endpoint` when doing this:

```ts
const defs = await getDefinitions({
  appName: 'xx',
  token: process.env.UNLEASH_SERVER_API_TOKEN,
  url: 'hardcoded url string'
})
```

but doing
```ts
const defs = await getDefinitions({
  appName: 'xx',
})
```
works

**Comment by Tymek** [comment]
`url` parameter expects different value from `UNLEASH_SERVER_API_URL`. For `getDefinitions` you need to provide **full path** to the endpoint (usually ending with `/api/client/features`) and server API URL points to Unleash instance (`/api`).

I can't reproduce this issue. Please reopen with reproducible steps if it still occurs.

**Comment by mltsy** [comment]
This helped, thanks!

I was having the same problem, because I didn't realize I needed to add `/client/features` if providing the url as an option rather than in an env variable (I assumed they'd be the same, since they're both called "URL".  The configuration options would be a nice thing to document in the README, though I see it is JSDoc'd which would have been helpful, had I read those!

Is there any reason they are not treated the same?  (that is, why not allow just the API URL for both, and have `getDefinitions` append `/client/features` as needed per its implementation?)
